### ISSUE TITLE
tensorflow版本的DQN 训练好的模型，无法加载

### ISSUE THREAD

**Issue by jackson-liugang** [NovemberChopin/RL_Tutorial#2]
![image](https://user-images.githubusercontent.com/75605049/157871195-2ce599d0-935f-4699-9097-ecd1409b69e2.png)

**Comment by NovemberChopin** [comment]
会不会是TensorLayer版本的问题，使用readme中提到的版本试试

**Comment by jackson-liugang** [comment]
好的，谢谢
